# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: LeoEatle's World
subtitle: Do have faith in what you are doing.
author: Leo Eatle
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://leoeatle.me
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

#Custom Setting Start

# Site settings
SEOTitle: LeoEatle的博客 | LeoEatle's Blog
header-img: img/home-bg.jpg
email: liuyitao811@hotmail.com
description: "为什么我喜欢个人博客，因为博客才能代表你的态度"
keyword: "blog technology javascript front-end coding web"


# SNS settings
# RSS: false
weibo_username:     liuyitao811
zhihu_username:     leoeatle
github_username:    LeoEatle
twitter_username:   LeoEatle
facebook_username:  LeoEatle
linkedin_username:  怡涛-刘-485b67124

# Build settings
anchorjs: true                          

# if you want to customize anchor. check out line:181 of `post.html`


# Disqus settings
disqus_username: leoeatle

# Duoshuo settings
# duoshuo_username: leoeatleduoshuo
# Share component is depend on Comment so we can NOT use share only.
# duoshuo_share: true                     # set to false if you want to use Comment without Sharing


# Analytics settings
# Baidu Analytics
ba_track_id: 4cc1f2d8f3067386cc5cdb626a202900
# Google Analytics
ga_track_id: 'UA-114741658-2'            # Format: UA-xxxxxx-xx
ga_domain: leoeatle.github.io


# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "What a weired name"
sidebar-avatar: /img/avatar.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`


# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value


# Friends
friends: [
    {
        title: "Kaijun's Blog",
        href: "http://blog.kaijun.rocks"
    },{
        title: "Abruzzi's Wall",
        href: "http://blog.angular.in/"
    },{
        title: "liangyuekang's Blog",
        href: "http://www.liangyuekang.net/"
    },{
        title: "skk's Blog",
        href: "https://blog.skk.moe/"
    },{
        title: "Hux",
        href: "http://huangxuan.me/"
    },{
        title: "一只会飞的鱼",
        href: "http://supperjet.github.io/"
    },{
        title: "Mem.Wey's Blog",
        href: "https://memwey.github.io/"
    }
]


#Custom Setting End



# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: huxblog

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:LeoEatle/leoeatle.github.io.git
  branch: master

# service worker
# offline config passed to sw-precache.
service_worker:
  maximumFileSizeToCacheInBytes: 5242880
  staticFileGlobs:
  - public/**/*.{js,html,css,png,jpg,gif,svg,eot,ttf,woff,woff2}
  stripPrefix: public
  verbose: true
